function SVGS() {
  return (
    <div
      className="relative -z-1 opacity-22 blur-[7px]
"
    >
      <div className="absolute -left-70 -top-60 inset-0 w-full h-full">
        <svg className="w-80 h-10  " xmlns="http://www.w3.org/2000/svg">
          <rect
            x="10"
            y="10"
            width="80"
            height="18"
            rx="10"
            ry="10"
            fill="#fde047"
          />
          <rect
            x="100"
            y="10"
            width="180"
            height="18"
            rx="10"
            ry="10"
            fill="#e879f9"
          />
        </svg>
        <svg className="w-80 h-10 " xmlns="http://www.w3.org/2000/svg">
          <rect
            x="10"
            y="10"
            width="180"
            height="18"
            rx="10"
            ry="10"
            fill="#34d399"
          />
          <rect
            x="200"
            y="10"
            width="80"
            height="18"
            rx="10"
            ry="10"
            fill="#9ca3af"
          />
        </svg>
        <svg className="w-80 h-10 " xmlns="http://www.w3.org/2000/svg">
          <rect
            x="10"
            y="10"
            width="130"
            height="18"
            rx="10"
            ry="10"
            fill="#e879f9"
          />
          <rect
            x="150"
            y="10"
            width="130"
            height="18"
            rx="10"
            ry="10"
            fill="#fde047"
          />
        </svg>
      </div>
      <div className="absolute inset-0 w-full h-full -z-1">
        <svg className="w-80 h-10  " xmlns="http://www.w3.org/2000/svg">
          <rect
            x="10"
            y="10"
            width="80"
            height="18"
            rx="10"
            ry="10"
            fill="#fde047"
          />
          <rect
            x="100"
            y="10"
            width="180"
            height="18"
            rx="10"
            ry="10"
            fill="#e879f9"
          />
        </svg>
        <svg className="w-80 h-10 " xmlns="http://www.w3.org/2000/svg">
          <rect
            x="10"
            y="10"
            width="180"
            height="18"
            rx="10"
            ry="10"
            fill="#34d399"
          />
          <rect
            x="200"
            y="10"
            width="80"
            height="18"
            rx="10"
            ry="10"
            fill="#9ca3af"
          />
        </svg>
        <svg className="w-80 h-10 " xmlns="http://www.w3.org/2000/svg">
          <rect
            x="10"
            y="10"
            width="130"
            height="18"
            rx="10"
            ry="10"
            fill="#e879f9"
          />
          <rect
            x="150"
            y="10"
            width="130"
            height="18"
            rx="10"
            ry="10"
            fill="#fde047"
          />
        </svg>
      </div>
      {/* next pair */}
      <div className="absolute -left-70 top-60 inset-0 w-full h-full">
        <svg className="w-80 h-10  " xmlns="http://www.w3.org/2000/svg">
          <rect
            x="10"
            y="10"
            width="80"
            height="18"
            rx="10"
            ry="10"
            fill="#fde047"
          />
          <rect
            x="100"
            y="10"
            width="180"
            height="18"
            rx="10"
            ry="10"
            fill="#e879f9"
          />
        </svg>
        <svg className="w-80 h-10 " xmlns="http://www.w3.org/2000/svg">
          <rect
            x="10"
            y="10"
            width="180"
            height="18"
            rx="10"
            ry="10"
            fill="#34d399"
          />
          <rect
            x="200"
            y="10"
            width="80"
            height="18"
            rx="10"
            ry="10"
            fill="#9ca3af"
          />
        </svg>
        <svg className="w-80 h-10 " xmlns="http://www.w3.org/2000/svg">
          <rect
            x="10"
            y="10"
            width="130"
            height="18"
            rx="10"
            ry="10"
            fill="#e879f9"
          />
          <rect
            x="150"
            y="10"
            width="130"
            height="18"
            rx="10"
            ry="10"
            fill="#fde047"
          />
        </svg>
      </div>
      <div className="absolute top-125 inset-0 w-full h-full -z-1">
        <svg className="w-80 h-10  " xmlns="http://www.w3.org/2000/svg">
          <rect
            x="10"
            y="10"
            width="80"
            height="18"
            rx="10"
            ry="10"
            fill="#fde047"
          />
          <rect
            x="100"
            y="10"
            width="180"
            height="18"
            rx="10"
            ry="10"
            fill="#e879f9"
          />
        </svg>
        <svg className="w-80 h-10 " xmlns="http://www.w3.org/2000/svg">
          <rect
            x="10"
            y="10"
            width="180"
            height="18"
            rx="10"
            ry="10"
            fill="#34d399"
          />
          <rect
            x="200"
            y="10"
            width="80"
            height="18"
            rx="10"
            ry="10"
            fill="#9ca3af"
          />
        </svg>
        <svg className="w-80 h-10 " xmlns="http://www.w3.org/2000/svg">
          <rect
            x="10"
            y="10"
            width="130"
            height="18"
            rx="10"
            ry="10"
            fill="#e879f9"
          />
          <rect
            x="150"
            y="10"
            width="130"
            height="18"
            rx="10"
            ry="10"
            fill="#fde047"
          />
        </svg>
      </div>
    </div>
  );
}

export default SVGS;
