function SVGS() {
  return (
    <div className="absolute opacity-22 blur-[7px] z-4">
      <div className="absolute -left-25 sm:-left-0 md:left-10 lg:left-0 lg:-top-60 -top-80 inset-0 w-full h-full">
        <svg className="w-80 h-10  " xmlns="http://www.w3.org/2000/svg">
          <rect
            x="10"
            y="10"
            width="80"
            height="18"
            rx="10"
            ry="10"
            fill="#fde047"
          />
          <rect
            x="100"
            y="10"
            width="180"
            height="18"
            rx="10"
            ry="10"
            fill="#e879f9"
          />
        </svg>
        <svg className="w-80 h-10 " xmlns="http://www.w3.org/2000/svg">
          <rect
            x="10"
            y="10"
            width="180"
            height="18"
            rx="10"
            ry="10"
            fill="#34d399"
          />
          <rect
            x="200"
            y="10"
            width="80"
            height="18"
            rx="10"
            ry="10"
            fill="#9ca3af"
          />
        </svg>
        <svg className="w-80 h-10 " xmlns="http://www.w3.org/2000/svg">
          <rect
            x="10"
            y="10"
            width="130"
            height="18"
            rx="10"
            ry="10"
            fill="#e879f9"
          />
          <rect
            x="150"
            y="10"
            width="130"
            height="18"
            rx="10"
            ry="10"
            fill="#fde047"
          />
        </svg>
      </div>
      <div className=" absolute left-35 sm:left-96 md:translate-x-60 lg:translate-x-10 inset-0 w-full h-full -z-1">
        <svg className="w-80 h-10" xmlns="http://www.w3.org/2000/svg">
          <rect
            x="10"
            y="10"
            width="80"
            height="18"
            rx="10"
            ry="10"
            fill="#fde047"
          />
          <rect
            x="100"
            y="10"
            width="180"
            height="18"
            rx="10"
            ry="10"
            fill="#e879f9"
          />
        </svg>
        <svg className="w-80 h-10 " xmlns="http://www.w3.org/2000/svg">
          <rect
            x="10"
            y="10"
            width="180"
            height="18"
            rx="10"
            ry="10"
            fill="#34d399"
          />
          <rect
            x="200"
            y="10"
            width="80"
            height="18"
            rx="10"
            ry="10"
            fill="#9ca3af"
          />
        </svg>
        <svg className="w-80 h-10 " xmlns="http://www.w3.org/2000/svg">
          <rect
            x="10"
            y="10"
            width="130"
            height="18"
            rx="10"
            ry="10"
            fill="#e879f9"
          />
          <rect
            x="150"
            y="10"
            width="130"
            height="18"
            rx="10"
            ry="10"
            fill="#fde047"
          />
        </svg>
      </div>
      {/* next pair */}
      <div className="absolute -left-25 sm:-left-0 top-80 lg:-translate-y-20 inset-0 w-full h-full">
        <svg className="w-80 h-10  " xmlns="http://www.w3.org/2000/svg">
          <rect
            x="10"
            y="10"
            width="80"
            height="18"
            rx="10"
            ry="10"
            fill="#fde047"
          />
          <rect
            x="100"
            y="10"
            width="180"
            height="18"
            rx="10"
            ry="10"
            fill="#e879f9"
          />
        </svg>
        <svg className="w-80 h-10 " xmlns="http://www.w3.org/2000/svg">
          <rect
            x="10"
            y="10"
            width="180"
            height="18"
            rx="10"
            ry="10"
            fill="#34d399"
          />
          <rect
            x="200"
            y="10"
            width="80"
            height="18"
            rx="10"
            ry="10"
            fill="#9ca3af"
          />
        </svg>
        <svg className="w-80 h-10 " xmlns="http://www.w3.org/2000/svg">
          <rect
            x="10"
            y="10"
            width="130"
            height="18"
            rx="10"
            ry="10"
            fill="#e879f9"
          />
          <rect
            x="150"
            y="10"
            width="130"
            height="18"
            rx="10"
            ry="10"
            fill="#fde047"
          />
        </svg>
      </div>
      <div className="absolute left-35 top-160 sm:left-96 md:translate-x-60 lg:translate-x-146 lg:-translate-y-30 inset-0 w-full h-full -z-1">
        <svg className="w-80 h-10  " xmlns="http://www.w3.org/2000/svg">
          <rect
            x="10"
            y="10"
            width="80"
            height="18"
            rx="10"
            ry="10"
            fill="#fde047"
          />
          <rect
            x="100"
            y="10"
            width="180"
            height="18"
            rx="10"
            ry="10"
            fill="#e879f9"
          />
        </svg>
        <svg className="w-80 h-10 " xmlns="http://www.w3.org/2000/svg">
          <rect
            x="10"
            y="10"
            width="180"
            height="18"
            rx="10"
            ry="10"
            fill="#34d399"
          />
          <rect
            x="200"
            y="10"
            width="80"
            height="18"
            rx="10"
            ry="10"
            fill="#9ca3af"
          />
        </svg>
        <svg className="w-80 h-10 " xmlns="http://www.w3.org/2000/svg">
          <rect
            x="10"
            y="10"
            width="130"
            height="18"
            rx="10"
            ry="10"
            fill="#e879f9"
          />
          <rect
            x="150"
            y="10"
            width="130"
            height="18"
            rx="10"
            ry="10"
            fill="#fde047"
          />
        </svg>
      </div>
    </div>
  );
}

export default SVGS;
